### PR TITLE
add an onClickClose callback

### PR DESCRIPTION
**Pull request by eipark**
Particularly useful when using Messenger with applications that use react/a backing data store to render the messenger.

### CODE REVIEW

**Comment by eipark** [comment]
@Friss mind helping me get this published? @TrevorBurnham gave it a review.

**Comment by Friss** [comment]
I actually don't have merge permissions on hubspot org yet. @timmfin or @geekjuice Should be able to get this published.

**Comment by geekjuice** [comment]
@eipark Feel free to merge and I can publish it for you at `v1.5.0` :rocket:

**Comment by TrevorBurnham** [comment]
:+1:

**Comment by Friss** [comment]
Also be sure to compile the coffeescript file

**Comment by geekjuice** [comment]
Realized `messenger` isn't in the npm registry, but it can be installed via `npm install HubSpot/messenger`.

**Pull request merged**
